[package]
name = "route53-update"
version = "0.0.1"
edition = "2021"

[dependencies]
aws-config = "0.55.0"
aws-sdk-route53 = "0.25.1"
clap = { version = "4.2.1", default-features = false, features = ["std", "derive", "usage", "help"] }
time = "0.3.20"
tokio = { version = "1.27.0", features = ["macros"] }
